# Generated by Django 2.2.6 on 2020-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0015_auto_20200324_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
